### ISSUE TITLE
not working. 

### ISSUE THREAD

**Issue by Mr-CostlessClaw** [RileyGuy/Impressive#2]
I have SteamVR all set to stable. I moved Re-Sounding and Rug to rml-lib and impressive to rml-mod. There was no "Resonite" folder after download an unzipping. I have tried a few face tracking avies including the facebot. steamVR debug shows eye tracking. The port is 9000. Anything i am missing?

**Comment by BlueCyro** [comment]
Hi! Definitely try with the main release of 1.0.3 at the time of writing this, and make sure that the SteamVR eye and face tracking options are both in fact on. I've also fixed the folder structure and added some preliminary tongue support as of SteamVR beta 2.2.3.

**Comment by Mr-CostlessClaw** [comment]
I dropped the "Resonite" file into the game folder and launched Resonite. I have tested it with 3 avatars that show to have driven facial blendshapes. They do not respond. VRC shows to only having eyes as open or closed. 
I have also marked the tracking off and back on. No change.

**Comment by Mr-CostlessClaw** [comment]
ok. I have to use the alt port. I have eye tracking. I just don't think steamlink is getting my mouth tracking.

**Comment by BlueCyro** [comment]
Do be sure that both the eye and face tracking options are on in steam link - there *should* be separate options for the eye and face but it's been a bit since I looked at the panel

**Comment by Mr-CostlessClaw** [comment]
I did. As I mentioned that I disabled and reenabled the eye and face. It is probably something I have to contact steam over. My mouth tracking isn't shown in my debug. Only eye.
________________________________

**Comment by Ultranique** [comment]
**I would like to add that I am having a hard time following these instructions, which I feel I am usually pretty good at.**

First off, thank you for making this mod, as I purchased a Quest Pro specifically to use FT with Resonite. Having said that, I am at a loss as what is going on with the installation instructions.

1) I do not see a 'Resonite' folder when unzipping Impressive-main.zip, and I am confused as to which 'Resonite' folder that is being referenced here to drop on top of. If I drop the unzipped 'Impressive-main' folder into the Resonite folder under the Steam folder structure for the game, it just moves the whole folder to the root directory.

2) I have created the install locations for the ResoniteModLoader and moved the DLL file there, and can verify it is running in the log. I have no mods installed at the moment.

3) when you say _"Firstly, impressive depends on [Re-Sounding](https://github.com/RileyGuy/Re-Sounding) (by yours truly), and [Rug.Osc](https://bitbucket.org/rugcode/rug.osc) (by rugcode). Both are included with the download of this mod for your convenience.",_ do you mean they are part of your Impressive mod installation? I do not see these as part of the download in any of the sub folders. Since I do not see them, if I do download them, where do they go in the folder structure?

I would really appreciate some clarity as how to install this before I go mucking the Resonite folder up guessing where things may go. Thank you

**Comment by BlueCyro** [comment]
Closing as no longer needed since Resonite supports Quest Pro facetracking natively now.
